### ISSUE TITLE
Support a proper means for unsetting keys

### ISSUE THREAD

**Issue by ssokolow** [sagiegurari/cargo-make#100]
#### Problem Description

In order to port a part of my justfile, I'm trying to bind `tasks.clippy` to `cargo +nightly clippy` with the environment variable `CARGO_TARGET_DIR=target/nightly` to keep it from clobbering the stable build artifact cache... but I ran into the following problems:

1. The default definition of the task tries to install the `clippy` crate and dies because my default compiler is `stable`.
2. I can't use the usual approach for unsetting an overlaid value from other languages because TOML has no provision for `install_crate = null`.
3. If I rename my task to `tasks.clippyh` as a test, I get a failed attempt to install `cargo-+nightly`
4. If I try setting `script = ["cargo +nightly clippy"]` in `tasks.clippy`, I get `Invalid task, contains multiple actions`, which is back to the same problem. (`command = null` not being valid TOML)
5. That last one *does* work if I name the task `clippyh`, but now I'm stuck with a conundrum. Do I...

    1. Use a shell function which remaps `cargo make clippy` to `cargo make clippy-real` and passes through everything else, rather than simply `alias cm=cargo make`?
    2. Use the nuclear option of `skip_core_tasks = true` and remove my primary reason for seeing cargo-make as more desirable than just. (Even with the predefined actions, you're going to be seeing several more issues filed by me about reasons cargo-make falls short of my needs.)

#### Code Example

````toml
[tasks.clippy]
# TODO: Some means of unsetting `command` so this works
script = ["cargo +nightly clippy"]
env = { "CARGO_TARGET_DIR" = "target/nightly" }

````

#### Error Stack/Info (if any)

```
[cargo-make] INFO - cargo-make 0.11.3
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: clippy
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: clippy
[cargo-make] ERROR - Invalid task, contains multiple actions.
```

**EDIT:** I also just realized that removing the predefined `install_crate` will be important now that things like clippy are in the process of migrating from cargo-based distribution to rustup-based distribution.

**Comment by sagiegurari** [comment]
if clippy are moving away from cargo to standalone executable, than I cannot automatically install it for you.
basically if its a cargo plugin, i look at the command and install it, if missing, so with clippy being not a cargo plugin, that would no longer happen.
so cargo-make tries to help you by auto installing what is missing, but ya, i see in this case that its hurting because clippy is kinda not related to the rust version you are running with.

Until than, you will want to disable that automatic installation that is done by cargo make for plugins, so i guess maybe a new attribute:
````toml
install = false
```
should resolve that and you can set it in your extended task in your makefile.toml. no?
that I can do pretty easily, but only if it really help you out.

by the way, did clippy already move away from cargo?
if so, maybe i'll just update the predefined makefile to use the new clippy without cargo.
that would mean, that nothing would be auto installed by cargo.
I'm also open for pull request if you have a good solution for the predefined clippy task that is in the internal makefile.

**Comment by ssokolow** [comment]
> Until than, you will want to disable that automatic installation that is done by cargo make for plugins, so i guess maybe a new attribute:
>
>     install = false
>
> should resolve that and you can set it in your extended task in your makefile.toml. no?
that I can do pretty easily, but only if it really help you out.

I'd prefer a more general solution, such as an `inherit = false` which allows me to redefine individual predefined commands from scratch. This may not be the only time where replacing a `command` with a `script` would be useful.

> by the way, did clippy already move away from cargo?
> if so, maybe i'll just update the predefined makefile to use the new clippy without cargo.

[This internals thread](https://internals.rust-lang.org/t/clippy-is-available-as-a-rustup-component/) says that there should now be a `clippy-preview` component in the nightly channel, but, no matter what I've tried, I can't get my rustup to acknowledge its existence.

**Comment by sagiegurari** [comment]
inherit = false sounds like a cool solution and definitely useful!!!
I'll work on that. will probably be ready tomorrow or so...

**Comment by sagiegurari** [comment]
I'm senile. that's already implemented via clear attribute

**Comment by sagiegurari** [comment]
clear is now support on every task type, docs updated.
you can test it by using branch 0.12.0
please tell me if it works good for you.

**Comment by sagiegurari** [comment]
closing as it is now officially released.
