### ISSUE TITLE
Add `CARGO_MAKE_PREV_TASK_NAME` and `CARGO_MAKE_NEXT_TASK_NAME` env vars

### ISSUE THREAD

**Issue by SamuelMarks** [sagiegurari/cargo-make#1135]
### Feature Description
It would be handy to know these things.

### Describe The Solution You'd Like

Here's a quick solution:

```rs
let mut all_steps =
    Self::handle_before_each_and_after_each_tasks(&config, &steps)?.into_owned();
for idx in 1..all_steps.len() - 1 {
    let new_env_vals = indexmap::indexmap! {
        String::from("CARGO_MAKE_PREV_TASK_NAME") => EnvValue::Value(all_steps[idx-1].name.clone()),
        String::from("CARGO_MAKE_NEXT_TASK_NAME") => EnvValue::Value(all_steps[idx+1].name.clone())
    };
    match &mut all_steps[idx].config.env {
        Some(ref mut existing_env) => existing_env.extend(new_env_vals),
        None => all_steps[idx].config.env = Some(new_env_vals),
    };
}
```

Would be good to get your opinion before sending through a PR. Obviously there are edge-cases like each next task name being "after_each" and each previous task name being "before_each"; and what to do about parallel tasks. Still though, if each `before_each` is notifying that a task is about to be executed and each `after_each` is notifying that a task has finished; then it would behoove the software to know the name of said task.

**Comment by sagiegurari** [comment]
1. i think adding prev task is possible via plugin - https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage-plugins
2. not sure i can support adding next task env var since its not defined at that moment for example a task running duckscript that runs multiple tasks or in case of forking (which will also break the prev) and so on...

so i feel if i provide a solution, it would probably be a low quality one and a plugin might give you better results as you know both the plugin code and the build code to ensure it works.

**Comment by sagiegurari** [comment]
closing this for now based on my explanation. feel free to reopen for discussion
