### ISSUE TITLE
Support Azure Pipelines

### ISSUE THREAD

**Issue by LegNeato** [sagiegurari/cargo-make#116]
I figure we might as well have a task to track 😄 

* [ ] Coverage is not executed.
   Looks like Azure Pipelines sets [`TF_BUILD` to `True`](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts#system-variables), so we need to look for that in addition to `TRAVIS` = `true`
* [ ] codecov does not seem to support azure yet so it fails to upload reports without providing a token
* [ ] Add docs

**Comment by sagiegurari** [comment]
thanks!!!

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by LegNeato** [comment]
@kaylangan is the `TF_BUILD` env variable  what we should check to decide if we are running in azure pipelines? Or is there a better car to check?

**Comment by sagiegurari** [comment]
@LegNeato I want to have a azure ci docs in the readme same as travis, appveyor and gitlab.
What to contribute a PR from your experience?

coverage will be taken care of as a different issue.

**Comment by LegNeato** [comment]
Sure, I'll poke at it tomorrow afternoon.

**Comment by sagiegurari** [comment]
Small update on this one:
* updated the docs on how to setup cargo-make for azure
* updated based on your PR a new var CARGO_MAKE_CI and updated internal makefile to use that instead of TRAVIS so it will be enabled for azure as well 
* codecov shell script changes to support azure is not really part of cargo make itself and basically it should work if users put the needed token in the azure pipelines config so i think that would be out of scope of this issue.

**Comment by LegNeato** [comment]
Sorry, got busy and didn't get to this 😢

**Comment by sagiegurari** [comment]
don't worry, totally understandable.
i did get ideas from your PR which really helped me

**Comment by sagiegurari** [comment]
@LegNeato 0.16.1 has just been published with all changes except of course the fact that codecov shell itself might need fixing for azure pipelines.
therefore I'm closing this issue. if you need anything more, feel free to open a new issue. thanks for your help with the PR
