### ISSUE TITLE
[feat] URL/URI in task, maybe as new `script_runner`?

### ISSUE THREAD

**Issue by SamuelMarks** [sagiegurari/cargo-make#131]
#### Problem Description
Rather than only supporting inline code, why not have a path parameter? - How about going further, and making that path one of URL or URI (see [RFC for file URI](https://tools.ietf.org/html/rfc8089))?

If URL, allow for a SHA256 sum to specified.

#### Potential
cargo-make becomes a package manager 😮 

---

What do you think? 😃

**Comment by sagiegurari** [comment]
it's a cool idea which I was thinking about for some time but in the context of loading and extending other makefiles and not task scripts.
at the end, I decided instead of supporting urls which might be limited, giving the user the ability to write a script to load external makefiles however the user sees fit, for example wget, git clone, file copy and so on...

So in your case, you could put common scripts in some centralized makefile.toml and your projects could extend that common makefile.toml using load scripts.
you can than use or extend those tasks in your local makefile.toml

take a look at [load scripts](https://github.com/sagiegurari/cargo-make#usage-load-scripts) and tell me if it solves the issue.

I saw one person using it in few related open source projects to reduce duplicate code.
https://github.com/search?q=filename%3AMakefile.toml+load_script&type=Code

**Comment by SamuelMarks** [comment]
Yeah, I agree, but that approach is also limiting. Rust is winning a lot of the benchmarks, and is cross-platform, whereas `curl` or `wget` being present on Windows is less likely.

Well here's the thing, you've already talked about separating cargo-make from cargo https://github.com/sagiegurari/cargo-make/issues/69. The second you do that, the question will be: **why not turn this into a generic task runner**?

In terms of performance, by abstracting them out into cargo-make native primitives, you'd be able to do the following execution pipeline:

  1. Download/cache all URL/URI dependencies **in parallel**, to .cargo-make directory in root of this repo
  2. Traverse dependency graph, efficiently pruning out tasks already run (as you currently do)
  3. Expose relevant exit code at end, showing success/failure

Combine this with my binary packaging idea https://github.com/sagiegurari/cargo-make/issues/128, and you can support crazy cross-platform commands like:
```batch
> curl -SsL https://binaries/wordpress-<os>-<arch> -o wordpress.exe;`
> wordpress.exe /v 4.9.8 :: on *nix machines: ./wordpress --version 4.9.8
[Downloading dependent tasks]
[Downloading dependent assets]
[Installing]
[Setting up environment variables]
[Setting up Postgres & nginx services]
```

Because we're in Rust—and thanks to your nice parallelisable task design—this whole process would be crazily fast.

I've got other ideas to explore, once this part has been done.

But what I want to know is: your thoughts? ❗️ 😀

**Comment by sagiegurari** [comment]
cool. I'll try to see what can be done.

**Comment by sagiegurari** [comment]
instead of having over complex config in cargo make tasks, we can now use duckscript as inline script that has the ability to fetch resources via http and execute native commands.
so its possible to do this with 2 lines of inline duckscript.
it can even be enhanced to do more fetching types, but thats outside cargo-make.
so in a way, this is now supported with cross platform scripting.
