### ISSUE TITLE
Use tarpaulin with travis

### ISSUE THREAD

**Issue by D4nte** [sagiegurari/cargo-make#178]
#### Problem Description

I am trying to activate tarpaulin as part of my travis builds but I am having some issues.
Looking at the documentation, I did the following changes:

```
# .travis.yml
env:
  global:
    - CARGO_MAKE_RUN_CODECOV=true

# Makefile.toml
[tasks.coverage]
description = "Runs coverage using tarpaulin."
alias = "coverage-tarpaulin"
```
However, as you can see [here](https://travis-ci.com/comit-network/comit-rs/builds/97969255) this did not activate tarpaulin:
```
[cargo-make] INFO - Running Task: bench-ci-flow
[cargo-make] INFO - Running Task: ci-coverage-flow
[cargo-make] INFO - Running Task: stop-sccache
```

I have now added `CARGO_MAKE_CI=true`, [same issue](https://travis-ci.com/comit-network/comit-rs/builds/97969072)

You can checkout my PR [here](https://github.com/comit-network/comit-rs/pull/675) and [Makefile.toml](https://github.com/comit-network/comit-rs/blob/8e6b5a4e4927fd62c7cdb6c4b8eb41e92d6b24cd/Makefile.toml)

# Version
`[cargo-make] INFO - cargo make 0.16.1`

**Comment by sagiegurari** [comment]
you are running in a rust workspace.
for workspace, each member has its own makefile.
if not provided, you are basically using the core makefile which comes with cargo-make and not the workspace level makefile.

in order to member crates to automatically use the workspace makefile, you must add the following to your workspace level makefile:

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
```

you can see more about it in the [docs](https://github.com/sagiegurari/cargo-make#usage-workspace-extend)

You should not manually add CARGO_MAKE_CI or remove the coverage conditions as they protect you. I understood you did it temporarily in order to debug the issue.

With the new [sub task routing](https://github.com/sagiegurari/cargo-make#usage-task-command-script-task-examplesubtask) i added in 0.16.2 I might change how it works so you won't have to override and change alias but just set some env var which I think is easier.
but thats not related....

**Comment by sagiegurari** [comment]
just released 0.16.3 by the way where you can set to tarpaulin via env:

```toml
[env]
# can be defined as kcov, tarpaulin, ...
CARGO_MAKE_COVERAGE_PROVIDER = "tarpaulin"
```

however, you still need to fix what I mentioned in previous comment.

**Comment by sagiegurari** [comment]
sorry, seems I broken the coverage task in 0.16.2 so i'm fixing now....

**Comment by sagiegurari** [comment]
fixed in 0.16.5

**Comment by D4nte** [comment]
Lots of revisions. Thanks :)

**Comment by sagiegurari** [comment]
closing this one. if its still an issue please reopen.
