### ISSUE TITLE
[Feature Request] Add `--workspace` option

### ISSUE THREAD

**Issue by TimDiekmann** [sagiegurari/cargo-make#199]
Is it possible to add a `--workspace` option, which forces `workspace = true`, similar to `--no-workspace`, which forces `workspace = false`?

**Comment by sagiegurari** [comment]
by default, if a workspace is detected, its running as a workspace flow meaning each task is invoked for each member.

**Comment by TimDiekmann** [comment]
I know, however would it be possible to overwrite `workspace = false`?

I'd like to expose only a minimum of tasks and use the desired task twice, once on all members and once for the root.

**Comment by sagiegurari** [comment]
the scenario is to run same task on both workspace level and member in a single run?
i'm not sure what task is relevant for both, but maybe you could do the following in your workspace level makefile (in case members do not have a makefile and automatically extend the workspace level one)

```
[tasks.common-task]
# whatever....

[tasks.workspace]
workspace = false
env = { "CARGO_MAKE_MEMBER_TASK" = "member" } 
dependencies = ["common-task", "do-on-members"]

[tasks.member]
run_task = "common-task"
```

than you can run it 

```sh
cargo make workspace
```

Since workspace task is defined as workspace=false, it will ignore the fact that its a workspace and not invoked this task on the members and instead invoke it on the workspace level.
It will first invoke common (wihch is the common task you want to run both for each member and for workspace level), than it will invoke "do-on-members" which will invoke each member with the task defined in the env CARGO_MAKE_MEMBER_TASK which is "member"
Than each member is invoked with task "member" which runs the common task (you can actually skip this extra "member" task and invoke common directly)

**Comment by TimDiekmann** [comment]
Thanks, your solution works!
