### ISSUE TITLE
Compilation error on version 0.22.0

### ISSUE THREAD

**Issue by giacomocariello** [sagiegurari/cargo-make#273]
**Describe the bug**

Install fails with compilation errors E0505 and E0503.

**To Reproduce**

$ cargo --version
cargo 1.34.0
$ rustc --version
rustc 1.34.2
$ cargo install --force cargo-make

**Error Stack**

   Compiling cargo-make v0.22.0
error[E0505]: cannot move out of `directory` because it is borrowed
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-make-0.22.0/src/lib/installer/crate_version_check.rs:40:22
   |
38 |             let directory_path = Path::new(&directory);
   |                                             --------- borrow of `directory` occurs here
39 |             if directory_path.exists() && directory_path.is_dir() {
40 |                 Some(directory)
   |                      ^^^^^^^^^ move out of `directory` occurs here

error[E0503]: cannot use `valid` because it was mutably borrowed
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-make-0.22.0/src/lib/runner.rs:69:5
   |
63 |     let do_validate = || {
   |                       -- borrow of `valid` occurs here
...
69 |     valid
   |     ^^^^^ use of borrowed `valid`

error: aborting due to 2 previous errors

Some errors occurred: E0503, E0505.

**Comment by sagiegurari** [comment]
Thanks for reporting this.
I bump the rustc minimal version every now and then, usually due to cargo-make dependencies that also bump their minimal version.
in this case, cargo-make minimal version is now 36, not 34.

if you must use 34, you can use the prebuilt binaries I create for every new release.
I have binaries for linux, mac and windows available.
for 0.22.0 you can find them at: https://github.com/sagiegurari/cargo-make/releases/tag/0.22.0
so just extract the binary and put in your cargo bin directory and make sure you have execute permission for it.

**Comment by sagiegurari** [comment]
closing this one. if you still have an issue, you can reopen and we will see how to resolve.
