### ISSUE TITLE
namespace conflict with other cargo commands

### ISSUE THREAD

**Issue by dakom** [sagiegurari/cargo-make#351]
Naming tasks like `build` or `clean` causes a failure - seems there's some conflict between task names and cargo utility names?

**Comment by sagiegurari** [comment]
what do you mean? can you give an example error?

**Comment by dakom** [comment]
With this Makefile.toml:

```
[tasks.clean-okay]
script = ["echo hello!"]

[tasks.clean]
script = ["echo hello!"]

[tasks.build-okay]
script = ["echo hello!"]

[tasks.build]
script = ["echo hello!"]
```

Running the `clean-okay` or `build-okay` tasks works fine. Running either `clean` or `build` errors with

```
[cargo-make] ERROR - Invalid task, contains multiple actions.
```

And then a large dump of what I guess is some serialized state

**Comment by sagiegurari** [comment]
ok, i get you.
so cargo make comes with a LOT of built in tasks so you won't have to write your own makefile (in some cases).
so those tasks like 'clean' are there for you.
when you define clean, it extends the core clean task, doesn't replace it.
to replace you can use the clear attribute (clear = true).
you can also remove all core tasks and start fresh if you want.
I think the documentation explains all that, and i'm sorry its so much text... too many features i suppose.

anyhow, back to your scenrio, if you define task clean with 'script' since it extends the core clean which has a 'command', it now has a task that does 2 things script + command which is invalid so it fails.

**Comment by dakom** [comment]
Ahh I see... and yeah, adding this to the toml fixes it:

[config]
skip_core_tasks = true

From my perspective, feel free to close the issue :)
