### ISSUE TITLE
env_scripts for shell

### ISSUE THREAD

**Issue by l4l** [sagiegurari/cargo-make#379]
I don't really know whether it's a unimplemented feature or a bug, but it seems that env exports from shell scripts (bash at least) doesn't work in `env_scripts = [ .. ]`. Here is the simple example for reproducing the case:

```bash
$ cat script.sh
export MY_SAMPLE_VAR=1234

$ cat build.toml
env_scripts = [
'''
#!/bin/bash

source "./script.sh"
echo Sample var at run script: $MY_SAMPLE_VAR
'''
]

[config]
skip_core_tasks = true

[tasks.check-script-env]
script = ["echo Sample var at task: ${MY_SAMPLE_VAR}"]

$ cargo make --makefile build.toml check-script-env
[cargo-make] INFO - cargo make 0.28.0
[cargo-make] INFO - Execute Command: "/bin/bash" "/tmp/kitsu/fsio/JAajsdYqJo.sh"
Sample var at run script: 1234
[cargo-make] INFO - Build File: build.toml
[cargo-make] INFO - Task: check-script-env
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Running Task: check-script-env
Sample var at task:
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Build Done in 0 seconds.
```

**Comment by sagiegurari** [comment]
correct, you need to use duckscript for that.
since its embedded inside cargo make, it can modify the env.
that's actually the reason i created this feature for :)

**Comment by sagiegurari** [comment]
looking at the docs, it seems i mentioned that. give it a try.

**Comment by l4l** [comment]
I see, so it's only possible with duckscript, that make sense then. There is also `@shell` runner, maybe it can handle similar thing? And as for common scrpts, I guess, it might be possible to look at the difference in all env vars before and after running `env_scripts`, wouldn't it?

**Comment by sagiegurari** [comment]
child process can't modify parent and parent can't see the env of the child so.... that's tricky.
that's why i gave the ability to run an embedded script.
duckscript is really simple shell like lang that has easy access to env, filesystem and so on. if there are limitations that are blocking you, please point them out so i can try to help out

**Comment by l4l** [comment]
Oh, indeed, you cannot simply eval this script without interpreter, right. Though it still should be possible explicitly setting child env vars and pass back new values via stdout.

My case is quite simple: before every task I need to set-up env vars that provided by third-party (e.g. `script.sh` in example above).

**Comment by sagiegurari** [comment]
before every task you need to call 3rd party sh?
is it same shell?
if so, you could have a task that sources that shell and then calls cargo make as another child

**Comment by l4l** [comment]
> before every task you need to call 3rd party sh?

Well, it basically environmental path-es (e.g. PATH, LD_LIBRARY_PATH, etc), but defined in shell script, so yes those should be defined. I guess some of the tasks don't really need these vars, but those are minority, so I thought it would be easier to simply define such envs as globals.

> is it same shell?

Didn't really get the question. In my case everything can be handled only by sh.

> if so, you could have a task that sources that shell and then calls cargo make as another child

Sounds like quite a clumsy solution. I think I'd better copy-paste vars from the script or maybe dig into duckscript.

**Comment by sagiegurari** [comment]
ya, its not fun solution sorry.
if those are not really before every task, you could migrate it into cargo-make.
if its a complex script that may change a lot in the future, maybe best way is to have some script source it and then call cargo-make.
there isn't much magic that can easily be done at the moment, sorry.

**Comment by sagiegurari** [comment]
i'm closing this for now, as i don't have and not sure i will have a good solution for importing shell scripts and running them embedded and not as child processes.
there are the following solutions:
* using duckscript
* using env table in makefile
i know it doesn't fit your needs as you have 3rd party scripts, but thats all i can do.
there are easy solution from outside cargo make meaning you have a bash script that sources that 3rd party script and then calls cargo make but since its outside my control i can't do much here.
