### ISSUE TITLE
Conditions are not respected for task with dependencies

### ISSUE THREAD

**Issue by theduke** [sagiegurari/cargo-make#42]
```toml
[tasks.whatever]
condition = {channels = ["stable"]}
dependencies = [
    "some",
    "deps",
]
```

I would expect the condition to block the whole task from running, which it does for a task with a `script` definition, but not for a task with dependencies.

I read the documentation and it says this is the intended behaviour, but I find this very weird. It makes running tasks conditionally kind of awkward for workspaces, because you have to define a wrapper task with `run_task` in every workspace member just to enable checking a condition.

Wha'ts the reasoning behind this behaviour?

---
ps: my workaround for now was to do this:

```toml
[tasks.scoped-ci-flow]
description = "CI task will run cargo build and cargo test with verbose output"
dependencies = [
    "pre-ci-flow",
    "pre-build",
    "build-verbose",
    "post-build",
    "pre-test",
    "test-verbose",
    "post-test",
    "ci-coverage-flow",
    "post-ci-flow"
]

[tasks.ci-flow]
condition = { channels = ["nightly"] }
run_task = "scoped-ci-flow"
dependencies = []
```

**Comment by sagiegurari** [comment]
Your workaround is actually the documented way to do it and the way I do it :)

The reason is that you may define the same dependency for multiple tasks.
When invocation starts, I create a sort of execution plan of the task you want to invoke and its dependencies and their dependencies and so on...
They are not even triggered in the order you defined them as maybe in your example post-ci-flow is a also a dependency of pre-ci-flow and therefore actually triggered first and not last.
I need to ensure those dependencies those cause a cycle and that they are not triggered multiple times.

Think of following:
````
[tasks.start]
dependencies: ['a', 'b', 'c']

[tasks.a]
dependencies: ['b', 'c']
condition: some condition that is never met!!!
````

If you run start, it would first run 'a', you would think that if a is not invoked b and c are not either, but b and c are invoked because they are also dependencies of start.
If they wouldn't the user wouldn't know why, after all it was defined in start.

from technical point of view, execution plan is created BEFORE execution, while conditions are verified during specific task execution (for example I check env var is NOW set and not at boot of cargo-make as some other task might set it up), so when I'm running some task, at that point, I don't even care about its dependencies, they were already executed.

run_task is different, it starts a new sub flow which has its own execution plan and can allow you to invoke same task twice (also documented).
Therefore it is used to wrap a conditional flow as you can block the entire run_task.

Hope it makes a bit more sense. Understand the confusion that is why I documented it and created a specific sub section for documentation on conditional sub flow.

Question I have is, is there a better way to setup the makefile? what fails? maybe that only needs to be modified with a condition.

**Comment by sagiegurari** [comment]
Ok,, just read your comment about the entire flow being off for specific module.
I'll think of someway of making that easier for workspaces.

**Comment by sagiegurari** [comment]
I'm thinking on maybe you could implement the init task and there define which workspace members you want to bypass.
your script would run only if the condition is met (meaning if rust is not nightly) and than i'll modify the workspace support to bypass specific members if told so.
that should make things short and clean.
Something like

your makefile.toml on the workspace level
````
[tasks.init]
condition = { channels = ["beta", "stable"] }
env = { "CARGO_MAKE_WORKSPACE_SKIP_MEMBERS" = "juniper_rocket;anothermodule;andanother" }
````

Since init is always invoked, it should not break anything.

**Comment by theduke** [comment]
I understand the reason behind this now, and it somewhat makes sense to me.

But, the whole system with env vars seems pretty hacky to me. I guess cargo-make would have embedded support for Rust workspaces to make this cleaner, and create a new "scope" for each workspace member at runtime rather then re-invoking itself again.

Also, I checked the `do-on-members` task. I don't think `export` works in the windows shell?

**Comment by sagiegurari** [comment]
scope is nice, i try to avoid too much code complexity but i'll think of it.
not sure I'll have time for that redesign in the coming few weeks.

as for export, you are right, but its only used for the coverage which currently is anyway not supported on windows and has conditions in the tasks to prevent its execution on windows.
however, if you look carefully I use
````toml
script_runner = "@shell"
````
which allows me to convert simple linux scripts to windows batch, so basically you will have SET commands there in runtime.

**Comment by sagiegurari** [comment]
[docs for @shell](https://github.com/sagiegurari/cargo-make#usage-task-command-script-task-exampleshell2batch)

**Comment by sagiegurari** [comment]
closing this one for now. will follow up via #44
