### ISSUE TITLE
workspace support redesign

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/cargo-make#44]
Internal workspace member handling of sub flows instead of running sub cargo-make processes per member.

**Comment by sagiegurari** [comment]
Based on discussion in #43

**Comment by sagiegurari** [comment]
based on discussions in #42

**Comment by azriel91** [comment]
Related to this, I noticed this:

* I have a virtual repository root crate (i.e. no source code), just `Cargo.toml` with member declarations
* When running`cargo make --no-workspace workspace-coverage`, `CARGO_MAKE_CRATE_FS_NAME` is empty
* The `coverage-kcov` task then tries to run every file under `target/debug/deps` because the glob doesn't have the crate name prefix

The noise can go away by adding a guard:

```bash
echo "Running unit tests from directory: ${BINARY_DIRECTORY}"
if [ -n "${CARGO_MAKE_CRATE_FS_NAME}" ]; then
    for file in ${BINARY_DIRECTORY}/${CARGO_MAKE_CRATE_FS_NAME}*
    do
        if "$file" ; then
            echo "Running file: $file"
            kcov --include-pattern=${CARGO_MAKE_WORKING_DIRECTORY}/src/ "$KCOV_EXCLUDE_LINE_ARG" "$KCOV_EXCLUDE_REGION_ARG" "$TARGET_DIRECTORY" "$file" || true
        fi
    done
fi
```

However the next issue I hit which relates to this ticket again, is when developing an interactive application binary crate, the `<crate_name>-ha5hc0d3` binaries inside `target/debug/deps` aren't all test binaries &mdash; `cargo` (or is it `rustc`?) puts the binary in that directory as well.

In test code, I can send input to the application and make it go away, but the coverage task doesn't know which `<crate_name>-ha5hc0d3` is a test vs which is the interactive application, as the glob would match both, which means we need a better way of merging coverage.

That last problem is hard, because I don't see how to distinguish what's a test binary and what's not, though I do note that in `target/debug`, there are also `<crate_name>-ha5hc0d3` binaries, and the binary that is not a test is just `target/debug/<crate_name>` without the `-ha5hc0d3`, so maybe changing the `BINARY_DIRECTORY` to that would work.

**Comment by sagiegurari** [comment]
@azriel91 thanks for all the input. I'll split each item to a separate issue and we will see how to resolve each problem. You already gave good ideas, so will probably it will based on them, just with more control to the crate developer via env vars.

**Comment by sagiegurari** [comment]
@theduke I have been thinking about this one for some time, and splitting workspace builds to sub processes does have its advantages, mostly regarding isolation.
For example if a workspace has 2 members.
The first has tests which are not thread safe so it has a definition in its Makefile.toml of a rust env var which sets the test threads to 1.
when the second member build is running, since its same process it will be impacted and its tests will run much slower.
So overall, I believe that keeping it to separate sub processes seems like a better design.

**Comment by sagiegurari** [comment]
I'll be closing this item. I think the current design gives stability and isolation for each member which is important.
If there are issues/ideas/suggestions, we can reopen this.

**Comment by azriel91** [comment]
Related to this and #55, since coverage is collected by running executables in the target/debug directory, I tried making the binary discovery restricted to the current crate's name:

```
echo "Running tests from directory: ${BINARY_DIRECTORY}"
for file in $(find "${BINARY_DIRECTORY}" -maxdepth 1 -type f | grep -v "\.d$\|\.rlib$\|\.so$" | grep -e "^${CARGO_MAKE_CRATE_NAME}-[a-z0-9]*")
do
    echo "Running file: $file"
    kcov # ... rest of args
done
'''
```

By limiting the binaries run to the matching crate name, workspace coverage time drops from 20 seconds to 9 seconds (and this is a relatively small repo &mdash; 4 crates in total right now). This performance gain makes me want to make this optimization because my repository is going to grow quite a bit.

Using that approach, integration test binaries are not run unless it has exactly the crate's name (which means only one `tests/<crate_name>.rs` integration test. However, we can make that `find | grep` expression configurable, which allows people to express their own convention for discovering binaries per crate, for example I might want to change the grep at the end to be `grep "^${CARGO_MAKE_CRATE_NAME}\(-[a-z0-9]*\)\?-[a-f0-9]*"`

---

Also, relating more to the subflow vs sub processes part in the original post, I figured out why my task overrides weren't working:

```
virtual_workspace
  |- Makefile.toml  # override was in here
  |
  |- crate/lib1
      |- Makefile.toml  # whereas you need to override in every workspace member
```

I tried creating symlinks from every member to the top level Makefile.toml so I didn't have to duplicate the overridden task but `cargo make` didn't take that; it worked when I copy pasted Makefile.toml everywhere.

This one's trickier to solve, maybe have an "inherit from workspace" feature.

**Comment by sagiegurari** [comment]
Sounds good to me. If you wish to run few more tests and create a pull request I'll be happy to merge it in

**Comment by sagiegurari** [comment]
created issue #59 to track this
