### ISSUE TITLE
Ability to list the tasks in my toml file

### ISSUE THREAD

**Issue by bobhenkel** [sagiegurari/cargo-make#480]
### Feature Description
So far all I can find is ``` makers --makefile ./my-build.toml --list-all-steps ``` which returns all kind of tasks I didn't create and none that are in my toml file.

I want to be able to list my tasks and ideally have a description show up next to them. Something similar to what you see people do with ``` make list ```.  My use case is coming from using this tool as a general purpose task runner, the tasks I run may have nothing to do with building or testing rust code, if that helps at all.

### Describe The Solution You'd Like
``` # makers --makefile ./my-build.toml list
      # **Tasks**
      # build - will build your code
      # build-docker - will build your docker image
      # bye - will echo bye
      # hello - will echo hello
      
```

Thanks
Bob

**Comment by bobhenkel** [comment]
I do see my tasks show up under No Category section, so maybe if I can figure out how to create a category that my tasks will be in I can filter everything else out?  Still seems kind of complicated for must wanting to list my tasks.

**Comment by sagiegurari** [comment]
* you see more tasks than you defined, because you automatically get a lot of the built in tasks in cargo-make. this allows you to use cargo make without the need of writing any makefile at all. if you want to not to have any of the built in core tasks and write everything from scratch, add the following to your makefile

```toml
[config]
skip_core_tasks = true
```

as mentioned in this section: https://github.com/sagiegurari/cargo-make#disabling-predefined-tasksflows

most core tasks are for rust (not all) so maybe you should add it.

* if you want your tasks to have some category, add **category** attribute to your tasks, for example:

```toml
[tasks.build]
description = "Runs the rust compiler."
category = "Build"
command = "cargo"
args = ["build", "--all-features"]
```

Naturally don't forget the description attribute as well

**Comment by sagiegurari** [comment]
also if your make file is named Makefile.toml its automatically picked up and all cli commands do not need the --makefile argument.
in your case, it means:

```sh
makers --list-all-steps
```

**Comment by bobhenkel** [comment]
Thanks! This is exactly what I was looking for.  Really liking cargo-make, even for non-rust things.

Really appreciate your work on this!

Thanks again!
Bob

**Comment by Bronson-Brown-deVost** [comment]
I know that this is closed, but as a forgetful person I would still like a clean and simple `cargo make --list-tasks`. I am always forgetting the exact names, so I have been using `cat Makefile.toml | grep tasks`,  which admittedly works fine. Also `skip_core_tasks = true` works nicely as @sagiegurari pointed out above.  If there is any interest, I am willing to take a stab at a PR. Expected output would be the same as `cargo make --list-all-steps` with `skip_core_tasks = true` (without having to add that to the config section of your makefile).
