### ISSUE TITLE
Broken makers output formatting in terminal (Windows)

### ISSUE THREAD

**Issue by MartinKavik** [sagiegurari/cargo-make#533]
### Describe The Bug
Broken `makers` output formatting in terminal. Probably only on Windows (git bash, ps, cmd)

![image](https://user-images.githubusercontent.com/18517402/112619073-2628aa00-8e27-11eb-9d40-a4061e521c97.png)

### To Reproduce
Run `makers` on Windows.

### How to resolve it

We were debugging it in [Trunk](https://trunkrs.dev/) and [this code](https://github.com/thedodd/trunk/blob/7b3cdde99daafd5bccdf7dab5bc742a3bba2a5bb/src/main.rs#L20-L23) (+ related dependency) should be enough to resolve it:
```rust
#[cfg(windows)]
if let Err(err) = ansi_term::enable_ansi_support() {
    eprintln!("error enabling ANSI support: {:?}", err);
}
```
_Note:_ `cargo make` works well, I assume `cargo` calls similar command by itself.

---

OT: Hi @sagiegurari. I'm just integrating `cargo-make` to https://github.com/MoonZoon/MoonZoon - `cargo make` is still the best task runner 🙂

**Comment by sagiegurari** [comment]
@MartinKavik  thanks a lot for reporting this.
i just tried on linux and both work ok and i don't have a windows box to try this on :(
its so strange that only makers fails on windows.
if you have the ability to help here and maybe provide a PR with a fix that would be amazing, otherwise i'll probably be blocked on this one.

**Comment by sagiegurari** [comment]
this is now released.
