### ISSUE TITLE
coverage-flow raise errors for binary projects with strict CLI arguments handling

### ISSUE THREAD

**Issue by elonca** [sagiegurari/cargo-make#552]
Hi,

First, thank you for developing such a good tool!

### Describe The Bug

I got an issue with the coverage-flow task for projects producing binaries for which unknown CLI arguments raise errors.
During the coverage-flow task, an error appears just like if the binary was invoked with wrong arguments.

### To Reproduce

Cargo.toml:

```toml
[package]
name = "cargo-make-cov-bug"
version = "0.1.0"
authors = ["emmanuel lonca"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
```

main.rs:

```rust
use clap::App;

fn main() {
    App::new("My Super Program").get_matches();
}

```

First, execute `cargo make` (no issue at this point):

```
[cargo-make] INFO - cargo make 0.32.17
[cargo-make] INFO - Project: cargo-make-cov-bug
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Execute Command: "cargo" "fmt"
[cargo-make] INFO - Execute Command: "cargo" "build" "--all-features"
   Compiling libc v0.2.94
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling vec_map v0.8.2
   Compiling textwrap v0.11.0
   Compiling atty v0.2.14
   Compiling clap v2.33.3
   Compiling cargo-make-cov-bug v0.1.0 (/home/lonca/projects/cargo-make-cov-bug)
    Finished dev [unoptimized + debuginfo] target(s) in 5.60s
[cargo-make] INFO - Execute Command: "cargo" "test" "--all-features"
   Compiling cargo-make-cov-bug v0.1.0 (/home/lonca/projects/cargo-make-cov-bug)
    Finished test [unoptimized + debuginfo] target(s) in 0.44s
     Running target/debug/deps/cargo_make_cov_bug-3ae0a44675a0669e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

[cargo-make] INFO - Build Done in 6.54 seconds.
```

Then, `cargo make coverage-flow`:

```
[cargo-make] INFO - cargo make 0.32.17
[cargo-make] INFO - Project: cargo-make-cov-bug
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: coverage-flow
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: setup-sudo-env
sudo enabled: true 
[cargo-make] INFO - Running Task: coverage-kcov
Working Directory: /home/lonca/projects/cargo-make-cov-bug
Target Directory: target/coverage
Running tests from directory: target/debug/deps
Test binary filter regex: cargo_make_cov_bug-[a-z0-9]*$\|test_[_a-z0-9]*-[a-z0-9]*$\|[a-z0-9]*_test-[_a-z0-9]*
Test Files:
target/debug/deps/cargo_make_cov_bug-b1357a642ff7f500
target/debug/deps/cargo_make_cov_bug-3ae0a44675a0669e
Running coverage for file: target/debug/deps/cargo_make_cov_bug-b1357a642ff7f500
[cargo-make-cov-bug.zip](https://github.com/sagiegurari/cargo-make/files/6390873/cargo-make-cov-bug.zip)
error: Found argument '--test-threads' which wasn't expected, or isn't valid in this context

USAGE:
    cargo_make_cov_bug-b1357a642ff7f500

For more information try --help
Running coverage for file: target/debug/deps/cargo_make_cov_bug-3ae0a44675a0669e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

[cargo-make] INFO - Build Done in 1.11 seconds.
```

It seems that the `--test-threads` argument is passed to the binary although it should not.
Running the same command with the verbose flag makes me think the problem occurs while running kcov.

```
[...]
Running coverage for file: target/debug/deps/cargo_make_cov_bug-b1357a642ff7f500
+ kcov --include-pattern=/home/lonca/projects/cargo-make-cov-bug/src/ --exclude-line=kcov-ignore --exclude-region=kcov-ignore-start:kcov-ignore-end target/coverage/1 target/debug/deps/cargo_make_cov_bug-b1357a642ff7f500 --test-threads 1
error: Found argument '--test-threads' which wasn't expected, or isn't valid in this context
[...]
```
You can find below an archive with the example project and the full logs.

[cargo-make-cov-bug.zip](https://github.com/sagiegurari/cargo-make/files/6390894/cargo-make-cov-bug.zip)

**Comment by sagiegurari** [comment]
@elonca thanks a lot for the feedback.
i'll try to explain what you are seeing (i hope) and why so we can understand if there is an issue and if there is, how to resolve it.

for coverage, by default, i use kcov.
i loop over executables and run kcov on them.
for each executable a report is generated and if you are in CI codecov will grab all of them and upload.

how do i know which executables to run? i don't.
I run all executables defined by this regex:
https://github.com/sagiegurari/cargo-make/blob/master/src/lib/descriptor/makefiles/stable.toml#L20

what is that test--threads arg? so tests are wrapped as executables which run the rust test runner with your tests.
and it knows to accept that flag to make tests run in parallel or single thread.

how did your app executable get into all of this?
so the regex by default includes your crate name because test executables are generated like that.
so on the way, it picked up your real app executable as well.
when running your app executable it will fail, but for other test executables it will not.

is the failure when running the real app executable an issue? 
no. i know some executables will fail because i can't really detect which ones are valid and which are not, so i ignore such errors.
all i really care about, is that the valid executables will generate the coverage report.
if some executable fails, its fine.

**Comment by elonca** [comment]
OK, I think I understand what's going on.

Correct me if I'm wrong:
 - one executable is produced for the actual program (just called "program" below), and some other executables are created for tests ("tests" below)
 - as it is difficult to differentiate the program from tests, kcov is run on all executables
 - since the actual coverage is built from the union of individual coverages, running kcov on the program does not change the coverage measure in a negative way.

Now I understand this process, I'm OK with the fact the error I pointed out is not really one.

However, I think running kcov on the program can produce other unwanted behaviors.
Take for example a program that waits for an action to continue its execution:

```rust
use std::io;

fn main() {
    println!("What's your name ?");
    let mut name = String::new();
    io::stdin().read_line(&mut name).expect("IO error");
    println!("Hello {}!", name.trim());
}
```

In this case, the coverage flow process is stuck, waiting for a text line to be entered by the user.
That's quite annoying :-)

I may have found a way to differentiate the program from tests, taking advantage of the fact target/debug contains the program (named after the crate).
On simple examples, one executable from target/debug/deps is a carbon copy of the one from target/debug, which allows to detect which executable from target/debug/deps is the program.
If this works for every program, then it allows to prevent running kcov on the program.

Do you think it could work ?

**Comment by sagiegurari** [comment]
ya that area always had pitfalls which is why i created that regex env var which than anyone can modify for their specific project to bypass any limitation.
if your solution is better, you can try it out by implementing it in the kcov task script which is a shellscript basically that runs over the config then finds files and runs kcov on them.

i see you forked, and I can't wait to see your PR :)
