### ISSUE TITLE
 Overriding default tasks non-trivial/annoying.

### ISSUE THREAD

**Issue by Cokemonkey11** [sagiegurari/cargo-make#56]
#### Problem Description

Creating a `default` task in project's `Makefile.toml` still pulls in dependencies from global default.

More generally, the global defaults are quite heavyweight and overprescriptive.

#### Code Example

````toml
$ cat Makefile.toml
[tasks.default]
dependencies = ["build"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = []
````

#### Error Stack/Info (if any)

```

$ cargo make
[cargo-make] INFO - cargo-make 0.9.2
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Setting Up Env.
[cargo-make] INFO - Running Task: init // ?? Why?
[cargo-make] INFO - Running Task: pre-format
[cargo-make] INFO - Running Task: format-stable
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--" "--write-mode=overwrite" "--force"
Unrecognized option: 'force'.
usage: rustfmt [options] <file>...

Options:
    -h, --help          show this message
    -V, --version       show version information
    -v, --verbose       show progress
        --write-mode [replace|overwrite|display|diff|coverage|checkstyle]
                        mode to write in (not usable when piping from stdin)
        --skip-children
                        don't reformat child modules
        --config-help   show details of rustfmt configuration options
        --config-path [Path for the configuration file]
                        Recursively searches the given path for the
                        rustfmt.toml config file. If not found reverts to the
                        input file path

[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by sagiegurari** [comment]
You just need to understand how to extend tasks and than it's pretty simple once you grasp the idea.

cargo make comes with the following default task definition:

````toml
[tasks.default]
description = "Default task points to the development testing flow"
alias = "dev-test-flow"
````

When you defined the following:

````toml
[tasks.default]
dependencies = ["build"]
````

It doesn't **replace** the **default** task definition, it **extends** it, so cargo-make sees actually:

````toml
[tasks.default]
description = "Default task points to the development testing flow"
alias = "dev-test-flow"
dependencies = ["build"]
````

Now, you need to read a bit on aliases, but in general, when cargo-make sees an alias, it ignores everything written in the task, and replaces everything with the alias task, so it becomes the **dev-test-flow** task in our case, so when you run it sees:

````toml
[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
dependencies = [
    "format-flow",
    "pre-build",
    "build",
    "post-build",
    "test-flow"
]
````

So what  you really want to do is the following, first define your own default task (in your Makefile.toml), for example:

````toml
[tasks.custom-default]
command = "cargo"
args = ["build", "--release"]
dependencies = []
````

Second point the default task to your new task as follows (in your Makefile.toml):

````toml
[tasks.default]
alias = "custom-default"
````

And that's it. 
Now in your very specific case, the build + release flag task already exists (but with additional --all-features flag which I hope is not an issue for you), which means you can skip the custom task definition and just do:

````toml
[tasks.default]
alias = "build-release"
````

But I do not recommend since you would probably want to add on top of that in the future and you don't want to mess up the build-release task for that.

You can read more on extending tasks and aliases in [this article](https://medium.com/@sagiegurari/automating-your-rust-workflows-with-cargo-make-part-2-of-5-extending-tasks-platform-overrides-1527386dcf87)

---

Now for the formatting error you got, so rustfmt is not backward compatible and gives errors based on the different crate you use and rustc version you use.
It's a real mess, so I try to do some sense in that mess and automatically use the right rustfmt for you based on the rust version you use.
However, for that I have to also use a new not backward compatible flag they added --force which fails for you since you use an older version of rustfmt.
Upgrading it should resolve that issue.

---

As for the default task being too heavyweight, it really depends and I admit that cargo make built in tasks are very opinionated, but rustfmt is really fast and doesn't bother me much when I develop and I like the fact that my code is always formatted per the standards.
Like I said, its very opinionated, but I like writing code and than running 1 command which formats, builds and tests it. It helps to see if the code is still ok, and in the process formats it so I continue working on nicely formatted code.

**Comment by Cokemonkey11** [comment]
> You just need to understand how to extend tasks and than it's pretty simple once you grasp the idea.

Here is what I think is not simple enough:

* Needing two defaults to make a new default
* Needing to read the default toml file to understand what's being extended (which isn't very convenient to find)
* The default toml file pollutes the namespace for extremely common command names like "default" and "build"

Here's my suggestion which resolves all these problems:

* allow `extend = ""` to use a scratch default make script
* make `alias` only work when the command has no other components (i.e. `alias` has lower priority, not higher priority)

TBF though, a better solution is to just provide templates [like](https://github.com/rust-lang-nursery/error-chain/blob/master/examples/quickstart.rs) [this](https://github.com/TeXitoi/structopt/blob/master/examples/basic.rs)

**Comment by sagiegurari** [comment]
> Needing two defaults to make a new default

Not really. it actually depends what you want to do. I gave you an example that in your case all you need to do it:

```toml
[tasks.default]
alias = "build-release"
```

> Needing to read the default toml file to understand what's being extended (which isn't very convenient to find)

For that I gave 2 cli options: --list-all-steps  and --print-steps to help understand what will happen.
Also documented an example how to find coverage related tasks for example:

```sh
cargo make --list-all-steps | grep "coverage-"
```

> The default toml file pollutes the namespace for extremely common command names like "default" and "build"

Ok, so I want to explain this one a bit.
I have used many different task runners and build tools at the past, from java ant and maven to js grunt and gulp to writing make files for C projects to writing shell scripts to using dev tools in R and so on...
You start a project/repo and define your build, for example with grunt, you define how to lint your code, format, test, do coverage and so on...
Everything is great until you open a second repo and copy paste the whole thing which feels really wrong. Afterwards another repo and another. 
Each time you use a really popular and powerful task runner but have to copy paste lots of instructions to make it work for you.

I wanted to do something different, 

* Make something that just works. No configuration, no code, no defining anything, just work. People use it without writing a single line, or creating a Makefile.toml. It gives you added value without you having to do anything. But at the same time, allow you to change everything as you see fit.
* Built in flows for development, CI, release and so on.... to have standard way to do thing with a way to customize the flow and push custom steps in the middle (using the pre/post empty tasks)
* Built in rules to when and how invoke tasks, for example some tasks are only supported on linux but we don't want to fail on windows so just allow automatic skipping of those and all of that already defined for you.

Now, you see it as polluting but I explained and defined a very specific [naming convention for tasks](https://github.com/sagiegurari/cargo-make#task-name-conventions) specifically not to pollute but to help. 
When you run cargo make build you expect it to run build and it does. So that is why i'm very strict regarding naming in the internal toml file.

What you are really looking for, is to write everything from scratch, and basically ignore everything in the internal toml file.
If we define that as the scope of the request, and since basically per this scope you will always have a Makefile.toml defined, I can support a new config attribute (a new attribute under the ```[config]``` section), which will allow you to ignore the internal makefile definitions.
I think that would give you what you need and at the same time would keep cargo-make the same and working out of the box for others.
Will that work for you?

**Comment by Cokemonkey11** [comment]
> I think that would give you what you need and at the same time would keep cargo-make the same and working out of the box for others.

Yes, I think so, although I wonder what you dislike about `extend = ""`.

Thanks for the thorough explanations.

**Comment by sagiegurari** [comment]
I prefer a flag which tells the user its meaning.
extend = "" might not seem so obvious to everyone.

**Comment by sagiegurari** [comment]
Sorry for taking so long, didn't have time to handle this one.
Anyhow, this is now implemented and published in version 0.9.4.
In order to prevent loading core tasks, simple add the following to your Makefile.toml

```toml
[config]
skip_core_tasks = true
```

**Comment by Cokemonkey11** [comment]
Works brilliantly 😎 happy for close if you are.

**Comment by sagiegurari** [comment]
Thanks for confirming

**Comment by JeanMertz** [comment]
Could it be that this isn't working (anymore)?

If I use this `Makefile.toml`:

```
[config]
skip_core_tasks = true
```

I get this:

```
cargo make --list-all-steps
[cargo-make] INFO - cargo make 0.21.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
No Category
----------
default - Empty Task
empty - Empty Task
```

However, if I then run `cargo make`, it still starts running the default tasks:

```
cargo make default
[cargo-make] INFO - cargo make 0.21.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: empty
[cargo-make] INFO - Running Task: workspace
[cargo-make] INFO - cargo make 0.21.0
[cargo-make] INFO - Using Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: development
[cargo-make] INFO - External file not found or is not a file, skipping.
[cargo-make] INFO - Running Task: init
[cargo-make] INFO - Running Task: pre-format
[cargo-make] INFO - Running Task: format
[cargo-make] INFO - Execute Command: "cargo" "fmt"
[cargo-make] INFO - Running Task: post-format
[cargo-make] INFO - Running Task: format-flow
[cargo-make] INFO - Running Task: pre-build
[cargo-make] INFO - Running Task: build
[cargo-make] INFO - Execute Command: "cargo" "build" "--all-features"
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s

... etc ...
```

Also, if I override `[tasks.test]`, it still keeps the default behaviour.

Could this be caused by the fact that I'm using a Cargo workspace? I only have one `Makefile.toml` at the root of the workspace though.

**Comment by sagiegurari** [comment]
its possible that something got messed up :(

**Comment by sagiegurari** [comment]
ok i understood now. so you are using a workspace (only read the start, ooops), so basically it will ignore that root makefile completely and go for each member and run cargo make there.
in order for that to take over, you need to have member crates makefile extend the workspace makefile, 
https://github.com/sagiegurari/cargo-make#usage-workspace-extend

so also add to that same makefile:

```toml
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
```

**Comment by JeanMertz** [comment]
Hmmm, I see. But I don't have (or need/want) member Makefiles, I only want to maintain one top-level Makefile for my workspace. Or is this not possible right now?

**Comment by sagiegurari** [comment]
the change i suggested is only in the top level makefile. no need for member makefiles. did you checkout the docs?

**Comment by JeanMertz** [comment]
I see. I did read the docs, and I'm pretty sure I tried that already, but it didn't work. But I'll try again tomorrow. Thank you for the help.
