### ISSUE TITLE
`--env-file` flag not working for 0.35.16

### ISSUE THREAD

**Issue by morenol** [sagiegurari/cargo-make#701]
### Describe The Bug
Using `cargo make <target> --env-file .env` works as expected with `cargo-make==0.34.0` and it does not work with cargo make `0.35.16`.  not sure about the previous versions of `0.35.X`

### To Reproduce

In any working worlspace try to use `--env-file` to set environment variables.

#### Details
Tested in macos and linux

**Comment by sagiegurari** [comment]
thanks, will check it.
i do remeber the docs state enfile=value and not envfile <space> value but both should work. so I'll test that

**Comment by sagiegurari** [comment]
@morenol ok, i get the issue.
you put
cargo make <target> --env-file .env
instead of
cargo make  --env-file .env <target>

if it worked on the past, is due to a bug and was not according to the readme docs.
all params/options must come before the target
the only thing after the target are the task args.
