### ISSUE TITLE
Does arm binary actually uploaded?

### ISSUE THREAD

**Issue by kachick** [sagiegurari/cargo-make#738]
### Describe The Bug

This is a question, `arm-unknown-linux-gnueabihf` binary is uploaded to anywhere?

https://github.com/sagiegurari/cargo-make/blob/7f3dc65cb46dc4d36dfcdcf65b8025c5437af7b0/README.md?plain=1#L164-L171

README said it is included in GitHub releases.
However looks nothing in both released assets and the publishing workflow.

https://github.com/sagiegurari/cargo-make/blob/7f3dc65cb46dc4d36dfcdcf65b8025c5437af7b0/.github/workflows/publish.yml#L14-L21

### To Reproduce

```console
$ curl https://api.github.com/repos/sagiegurari/cargo-make/releases/latest | jq '.assets | map(.name, .updated_at)'
[
  "cargo-make-v0.36.2-x86_64-apple-darwin.zip",
  "2022-10-18T21:05:18Z",
  "cargo-make-v0.36.2-x86_64-pc-windows-msvc.zip",
  "2022-10-18T20:56:59Z",
  "cargo-make-v0.36.2-x86_64-unknown-linux-musl.zip",
  "2022-10-18T20:47:28Z"
]
```

### Error Stack

```console
The error stack trace
```

### Code Sample

```rust
/// paste code here
```

**Comment by sagiegurari** [comment]
@kachick thanks for pointing out an issue in the readme.
at the past i did upload arm binaries to bintray or something like that. but that service no longer exists.
believe it or not, but my development machine is raspbarry pi 4 :) so arm is what i use all of the time.
I did start working on a build on arm CI machine to automate this but had issues with openssl.
however, that was really long ago, and since than 
1. i support pure rust tls
2. i support no tls
so i think i'm unblocked there and can continue the work on it.
i am not doing it via github actions as github do not provide arm machines :( 
i have the work i started somewhere and i can pick it up, but for now, you will have to do manual cargo install. sorry.

**Comment by sagiegurari** [comment]
#541

**Comment by kachick** [comment]
Thanks for sharing this background with me!

>believe it or not, but my development machine is raspbarry pi 4 :)

😮 Oh... I didn't know the Raspberry Pi was that powerful.
