### ISSUE TITLE
Question about packaging Makefile.toml with a crate

### ISSUE THREAD

**Issue by x37v** [sagiegurari/cargo-make#755]
I'm using cargo-make to generate example plugins with a library that I've been developing and I hope to allow others to use the library to create their own plugins with the cargo-make setup I've written but I'm not sure if that is possible.

Is it possible to add a `Makefile.toml` file to a crate on crates.io and somehow let a user extend it?
Do you have some other recommended mechanism for sharing `Makefile.toml` files?

**Comment by sagiegurari** [comment]
i'm not 100% sure of the use case so i'll throw some ideas and i'm not sure if they are relevant or not

1. cargo-make embeds some makefile tomls. when it reads an external file, it extends the internal ones. so you could package defaults and have user makefiles replace/extend those.
2. you can package toml files with the crate using the Cargo.toml includes attribute. however this is more for binaries than libraries. 
3. you can just provide an examples directory with different toml files so users can copy from.

**Comment by sagiegurari** [comment]
@x37v sorry for late reply.
what you could maybe do, is create a simple toml via echo like you did, but instead of having it do only extend to a file that does not exist, you can define it to load another file from github or something.

so you can do the following steps
1. via echo create makefile that downloads the real makefile from the web
2. call cargo-make to trigger the download

with duckscript [wget](https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md#std__net__WGet) it should support all platforms.

another way, is to create a simple make file, but instead of just extends, also add a [load script](rari/cargo-make#usage-load-scripts) that basically also calls duckscript to load the real file from github or somewhere else, and only then the extends is triggered to a local file.
if you want a real life example of that, you can take a look at:
https://github.com/sagiegurari/cargo-make-tasks/
its a lot more complex from what you need, but... its an example.
