### ISSUE TITLE
Local dependencies for cargo-make scripts

### ISSUE THREAD

**Issue by JohnScience** [sagiegurari/cargo-make#922]
### Feature Description

I would like to be able to use local dependencies in `@rust`-scripts in `Makefile.toml`. Without it, the script grows too big.

### Describe The Solution You'd Like

Ideally there should be a way to configure `@rust` runner to either

1. treat the path

```
//! ```cargo
//! [dependencies]
//! ensure_config = { path = "scripts/ensure_config" }
//! ```
```

not as `<tmp>/scripts/ensure_config` but as `<Makefile.toml dir>/scripts/ensure_config`. Let's call it "path resolution" strategy.

2. allow to copy the contents of  `scripts/` directory to the temporary dir. Let's call it "resource transfer" strategy.

### Code Sample

The code below should work:

```
[tasks.ensure_config]
script_runner = "@rust"
local_dep_strat = "path_resolution"
script = '''
//! ```cargo
//! [dependencies]
//! # ensure_config = { path = "scripts/ensure_config" }
//! open = "5"
//! toml = "0.7"
//! thiserror = "1"
//! ```
```

**Comment by sagiegurari** [comment]
by default cargo-make uses [rust-script](https://rust-script.org) to invoke these. so checkout if its possible to do it there and if not, ask for changes that can be reflected in the script/env.
one thing that might resolve your issue is the RUST_SCRIPT_BASE_PATH env but i'm not sure.

**Comment by sagiegurari** [comment]
closing for now.

**Comment by wmmc88** [comment]
@JohnScience were you able to find a solution to using local path dependencies with `rust-script`?

I was recently playing around with this today and `RUST_SCRIPT_BASE_PATH` is something that `rust-script` provides as the base path for local dependency resolution, but its not something that the user can modify.

Since `rust-script` dependencies are doc comments at the top of the script file, there seems like no simple built-in way for someone to modify something like this:
```rust
//! ```cargo
//! [dependencies]
//! my-local-crate = { path = "./crates/my-local-crate" }
//! ```
```

to something like this:
```rust
//! ```cargo
//! [dependencies]
//! my-local-crate = { path = "some/absolute/path/based/on/CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY /crates/my-local-crate" }
//! ```
```

Since the dependency is in a doc comment in a script block, it can't expand something like `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` or read the environment. Is the best thing to do here to pre-process the script block with a cargo-make plugin?

**Comment by JohnScience** [comment]
> @JohnScience were you able to find a solution to using local path dependencies with `rust-script`?
> 
> I was recently playing around with this today and `RUST_SCRIPT_BASE_PATH` is something that `rust-script` provides as the base path for local dependency resolution, but its not something that the user can modify.
> 
> Since `rust-script` dependencies are doc comments at the top of the script file, there seems like no simple built-in way for someone to modify something like this:
> 
> ```rust
> //! ```cargo
> //! [dependencies]
> //! my-local-crate = { path = "./crates/my-local-crate" }
> //! ```
> ```
> 
> to something like this:
> 
> ```rust
> //! ```cargo
> //! [dependencies]
> //! my-local-crate = { path = "some/absolute/path/based/on/CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY /crates/my-local-crate" }
> //! ```
> ```
> 
> Since the dependency is in a doc comment in a script block, it can't expand something like `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` or read the environment. Is the best thing to do here to pre-process the script block with a cargo-make plugin?

```toml
[tasks.ensure_cfg]
script_runner = "@shell"
cwd = "./"
script = '''
cargo run --manifest-path ./cargo-make-scripts/ensure_cfg/Cargo.toml
```

**Comment by wmmc88** [comment]
Turns out `rust-script` added `--base-path` in v0.30.0: https://github.com/fornwall/rust-script/issues/109
